var_password_minlen: 10
var_password_max_days: 45
var_password_max_days_mob: 365
var_password_min_days: 1

var_services_blacklist:
  - vsftpd
  - telnetd
  - tightvncserver
  - squid
  - tftpd
  - apache2

var_sudoers_groups_whitelist:
  - "sudo:x:27:ansible"
  - "admins:x:1001:ansible"

var_suid_whitelist:
  - "/usr/bin/passwd"
  - "/usr/bin/sudo"
  - "/usr/bin/newgrp"
  - "/usr/bin/chfn"
  - "/usr/bin/pkexec"
  - "/usr/bin/netkit-rlogin"
  - "/usr/bin/gpasswd"
  - "/usr/bin/ksu"
  - "/sbin/mount.cifs"
  - "/sbin/mount.nfs"
  - "/sbin/mount.ecryptfs_private"
  - "/bin/efibootmgr"
  - "/bin/fusermount"
  - "/bin/su"
  - "/bin/mount"
  - "/bin/umount"

var_log_skip_permissions_check: "dummy*"

var_sudo_logfile: "/var/log/sudo.log"

var_superusers: root
var_password_pbkdf2: grub.pbkdf2.sha512.10000.E3F286A301E64EB0234413E469860C9C4689184EDEB1116458D402A2709980F0BC1CAC8127217B5B5B94DD1E429F2FBC93220CE0460359116D08FE0E7387EB99.EF0E53D35560388021726E5F579ACA8F9AFF2C5AE2ACA06965042DCB86612F628D459016E9D3EFF0CEC9DEC0424A3FC2095E759BC9349BD3F02301E3D96FAF4D