- name: Remove outdate dist-upgrade flag file @remove_outdate_dist_upgrade_flag_file
  block:
    - name: Remove outdate dist-upgrade flag file Stat @remove_outdate_dist_upgrade_flag_file
      find:
        paths: /etc/ansible/
        patterns: dist-upgrade
        age: 30d
      register: result
    - name: Remove outdate dist-upgrade flag file File @remove_outdate_dist_upgrade_flag_file
      file:
        path: "{{item.path}}"
        state: absent
      with_items: "{{result.files}}"
  tags:
    - ws
    - remove_outdate_dist_upgrade_flag_file

- name: Switch to new kernel @switch_to_new_kernel
  block:
    - name: Switch to new kernel Apt
      failed_when: false
      apt:
        name: "{{var_switch_to_new_kernel}}"
        state: latest
    - name: Switch to new kernel Rm line
      lineinfile:
        dest: /etc/default/grub
        regexp: ^GRUB_DEFAULT=
        state: absent
      register: result
    - name: Switch to new kernel Update grub
      command: update-grub
      when: result.changed
  when: var_switch_to_new_kernel is defined
  tags:
    - ws
    - switch_to_new_kernel

- name: Apt dist-upgrade @apt_dist_upgrade
  ignore_errors: "{{ansible_check_mode}}"
  block:
    - name: Apt dist-upgrade Upgrade @apt_dist_upgrade
      apt:
        update_cache: yes
        upgrade: dist
      when: var_dist_upgrade
    - name: Apt dist-upgrade Remove flag @apt_dist_upgrade
      file:
        path: /etc/ansible/dist-upgrade
        state: absent
  tags:
    - ws
    - apt_dist_upgrade
