- name: Apt dist-upgrade
  block:
    - name: Apt dist-upgrade Check flag
      stat:
        path: /etc/ansible/dist-upgrade
      register: result
    - name: Apt dist-upgrade Upgrade
      apt:
        update_cache: yes
        upgrade: dist
      when: result.stat.exists
    - name: Apt dist-upgrade Remove flag
      file:
        path: /etc/ansible/dist-upgrade
        state: absent
  tags:
    - ws
    - apt_dist_upgrade      
