- name: Dpkg configure all
  check_mode: no
  changed_when: false
  shell: 'dpkg --configure -a'
  ignore_errors: yes
  when: ansible_os_family in ['Debian']
  tags:
    - ws
    - dpkg_configure_all

- name: Apt update
  command: apt update
  changed_when: false
  when: ansible_os_family in ['Debian']  
  tags:
    - ws
    - apt_update

- name: Rpm rebuilddb
  check_mode: no
  changed_when: false
  shell: 'rpm --rebuilddb'
  ignore_errors: yes
  when: >
    (ansible_os_family in ['RedHat', 'Rocky']) and
    ansible_distribution_major_version == "7"
  tags:
    - ws
    - rpm_rebuilddb

