- name: Dpkg configure all @dpkg_configure_all
  check_mode: no
  changed_when: false
  shell: 'dpkg --configure -a'
  ignore_errors: yes
  when: ansible_pkg_mgr == 'apt'
  tags:
    - ws
    - dpkg_configure_all

- name: Apt update @apt_update
  ignore_errors: "{{ansible_check_mode}}"
  command: apt update
  changed_when: false
  when: ansible_pkg_mgr == 'apt'
  tags:
    - ws
    - apt_update

- name: Rpm rebuilddb @rpm_rebuilddb
  ignore_errors: "{{ansible_check_mode}}"
  check_mode: no
  changed_when: false
  shell: 'rpm --rebuilddb'
  when: ansible_pkg_mgr == 'dnf'
  tags:
    - ws
    - rpm_rebuilddb

