- name: Connman masked @connman_masked
  block:
    - name: Connman masked Stop @connman_masked
      failed_when: false
      service:
        name: connman
        state: stopped
    - name: Connman masked Masked @connman_masked
      failed_when: false
      service:
        name: connman
        masked: yes
      notify: Networking restarted
    - name: Connman wait online masked Stop @connman_masked
      failed_when: false
      service:
        name: connman-wait-online
        state: stopped
    - name: Connman wait online masked Masked @connman_masked
      failed_when: false
      service:
        name: connman-wait-online
        masked: yes
      notify: Networking restarted
  tags:
    - ws
    - connman_masked

- name: Packagekit started @packagekit_started
  block:
    - name: Packagekit masked Masked @packagekit_started
      failed_when: false
      systemd:
        name: packagekit
        masked: no
    - name: Packagekit masked Stopped @packagekit_started
      failed_when: false
      service:
        name: packagekit
        state: started
  tags:
    - ws
    - packagekit_started

- name: Apt-daily.timer masked @apt_daily_masked
  block:
    - name: Apt-daily.timer masked Stopped @apt_daily_masked
      failed_when: false
      service:
        name: apt-daily.timer
        state: stopped
    - name: Apt-daily.timer masked Masked @apt_daily_masked
      failed_when: false
      service:
        name: apt-daily.timer
        masked: yes
  tags:
    - ws
    - apt_daily_masked

