- name: Post req install @post_req_install
  ignore_errors: true
  block:
    - name: Post req install Who @post_req_install
      changed_when: false
      shell: who | awk '{print $1}'
      register: logged_in_users
    - name: Post req install Uri @post_req_install
      failed_when: false
      uri:
        url: https://{{var_ansible_fqdn}}/post/{{item}}.post
        method: GET
        return_content: yes
        status_code: 200
        body_format: json
      register: users_pkgs
      with_items: "{{logged_in_users.stdout_lines | unique}}"
    - name: Post req install Set @post_req_install
      set_fact:
        pkgs_present: "{{(users_pkgs.results[0].content | from_json)['pkgs_present'] | intersect(var_post_req_apps)}}"
    - name: Post req install Package @post_req_install
      package:
        name: "{{item}}"
        state: present
      with_items: "{{pkgs_present}}"
  tags:
    - ws
    - post_req_install