- name: Ensure compilers are removed @compilers_are_removed
  ignore_errors: "{{ansible_check_mode}}"
  package:
    name:
      - g++
      - gcc
      - g++-6
      - gcc-6
      - gcc-8
    state: absent
  tags:
    - ws
    - sec
    - mob
    - compilers_are_removed
    - never
