- name: Get running kernel version @running_kernel_version
  changed_when: false
  shell: uname -r | cut -d '-' -f1-2
  register: running_kernel_version
  tags:
    - ws
    - running_kernel_version

- name: Ensure third-party repos are disabled @rm_third_party_repo
  ignore_errors: "{{ansible_check_mode}}"
  block:
    - name: Ensure third-party repos are disabled List dir @rm_third_party_repo
      find:
        paths: /etc/apt/sources.list.d/
        recurse: no
        file_type: file
        excludes:
          - "libreoffice-ubuntu-libreoffice-still-focal.list"
          - "dummy.list"
          - "sources.list"
      register: result
    - name: Ensure third-party repos are disabled Comment @rm_third_party_repo
      replace:
        dest: "{{item.path}}"
        regexp: '^(deb\s.*)'
        replace: '# \1'
      with_items: "{{ result.files }}"
  tags:
    - ws
    - rm_third_party_repo
