- name: Ensure third-party packages are installed @third_party_packages_are_installed
  failed_when: false
  package:
    name:
      - ganttproject
    state: latest
  tags:
    - ws
    - third_party_packages_are_installed
