- name: Unattended security upgrades @unattended_security_upgrades_deb
  ignore_errors: "{{ansible_check_mode}}"
  block:
    - name: Unattended security upgrades Present @unattended_security_upgrades_deb
      package:
        name: unattended-upgrades
        state: present
    - name: Unattended security upgrades Gather the package facts @unattended_security_upgrades_deb
      package_facts:
        manager: auto
    - name: Unattended security upgrades Enable service unattended-upgrades @unattended_security_upgrades_deb
      service:
        name: unattended-upgrades
        enabled: 'yes'
        state: started
    - name: Unattended security upgrades Ensure line in file @unattended_security_upgrades_deb
      lineinfile:
        dest: /etc/apt/apt.conf.d/50unattended-upgrades
        line: '        "origin=Debian,codename=${distro_codename},label=Debian-Security";'
        regexp: ^\s*\"origin=Debian,codename=\$\{distro_codename\},label=Debian-Security\"
        state: present
        create: true
        insertafter: Unattended-Upgrade::Origins-Pattern
  when: ansible_pkg_mgr == 'apt'
  tags:
    - ws
    - sec
    - mob
    - unattended_security_upgrades_deb

- name: Daily unattended upgrades @daily_unattended_upgrades_deb
  ignore_errors: "{{ansible_check_mode}}"
  block:
    - name: Gather the package facts @daily_unattended_upgrades_deb
      package_facts:
        manager: auto
    - name: Enable service unattended-upgrades @daily_unattended_upgrades_deb
      service:
        name: unattended-upgrades
        enabled: 'yes'
        state: started
  when: ansible_pkg_mgr == 'apt'
  tags:
    - ws
    - sec
    - daily_unattended_upgrades_deb

- name: Dnf automatic @unattended_security_upgrades_dnf
  ignore_errors: "{{ansible_check_mode}}"
  block:
    - name:  Dnf automatic Present @unattended_security_upgrades_dnf
      package:
        name: dnf-automatic
        state: present
    - name: Dnf automatic Replace update cmd @unattended_security_upgrades_dnf
      replace:
        dest: /etc/dnf/automatic.conf
        regexp: ^#?\s*(upgrade_type).*
        replace: '\1 = security'
    - name: Dnf automatic Replace download updates @unattended_security_upgrades_dnf
      replace:
        dest: /etc/dnf/automatic.conf
        regexp: ^#?\s*(download_updates).*
        replace: '\1 = yes'
    - name: Dnf automatic Replace apply updates @unattended_security_upgrades_dnf
      replace:
        dest: /etc/dnf/automatic.conf
        regexp: ^#?\s*(apply_updates).*
        replace: '\1 = yes'
    - name: Dnf automatic Replace apply updates @unattended_security_upgrades_dnf
      systemd_service:
        name: dnf-automatic.timer
        state: started
        enabled: true
  when: ansible_pkg_mgr == 'dnf'
  tags:
    - ws
    - sec
    - mob
    - unattended_security_upgrades_dnf
