- name: Unattended security upgrades
  block:
    - name: Unattended security upgrades Present
      package:
        name: unattended-upgrades
        state: present
    - name: Unattended security upgrades Gather the package facts
      package_facts:
        manager: auto
    - name: Unattended security upgrades Enable service unattended-upgrades
      service:
        name: unattended-upgrades
        enabled: 'yes'
        state: started
    - name: Unattended security upgrades Ensure line in file
      lineinfile:
        dest: /etc/apt/apt.conf.d/50unattended-upgrades
        line: '        "origin=Debian,codename=${distro_codename},label=Debian-Security";'
        regexp: ^\s*\"origin=Debian,codename=\$\{distro_codename\},label=Debian-Security\"
        state: present
        create: true
        insertafter: Unattended-Upgrade::Origins-Pattern
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
  tags:
    - ws
    - sec
    - mob
    - unattended_security_upgrades_deb

- name: Daily unattended upgrades
  block:
    - name: Gather the package facts
      package_facts:
        manager: auto
    - name: Enable service unattended-upgrades
      service:
        name: unattended-upgrades
        enabled: 'yes'
        state: started
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
  tags:
    - ws
    - sec
    - daily_unattended_upgrades_deb

- name: Yum cron
  block:
    - name: Yum cron Present
      package:
        name: yum-cron
        state: present
    - name: Yum cron Replace update cmd
      replace:
        dest: /etc/yum/yum-cron.conf
        regexp: 
        replace: 
    - name: Yum cron Replace apply updates
      replace:
        dest: /etc/yum/yum-cron.conf
        regexp: ^\s*\"origin=Debian,codename=\$\{distro_codename\},label=Debian-Security\"
        replace: 
  when: (ansible_distribution == "CentOS" or ansible_distribution == "OracleLinux") and
  ansible_distribution_major_version == "7"
  tags:
    - ws
    - sec
    - mob
    - unattended_security_upgrades_yum


