- name: Ensure package facts auto @package_facts_auto
  package_facts:
    manager: auto
  tags:
    - ws
    - package_facts_auto

- name: Remove specific package versions @remove_pkg_specific_version
  shell: "dpkg --remove --force-all {{item}}"
  when: (ansible_facts.packages[item] is defined) and (ansible_facts.packages[item][0].version == var_pkg_versions_absent[item])
  with_items: "{{var_pkg_versions_absent.keys() | list}}"
  ignore_errors: yes
  tags:
    - ws
    - remove_pkg_specific_version

- name: Present specific package versions @present_pkg_specific_version
  ignore_errors: yes
  package:
    name: "{{item}}"
    state: present
  with_items: "{{var_pkg_versions_absent.keys() | list}}"
  tags:
    - ws
    - present_pkg_specific_version


