- name: Enable service cron
  block:
    - name: Ensure cron is installed
      package:
        name: "{{'cron' if ansible_os_family in ['Debian'] else 'cronie'}}"
        state: present
    - name: Gather the package facts
      package_facts:
        manager: auto
    - name: Enable service cron
      service:
        name: "{{'cron' if ansible_os_family in ['Debian'] else 'crond'}}"
        enabled: 'yes'
        state: started
      when:
        - '"crond" in ansible_facts.packages'
  tags:
    - ws
    - sec
    - mob
    - service_cron_enabled
