- name: Enable service cron deb
  block:
    - name: Ensure cron is installed
      package:
        name: cron
        state: present
    - name: Gather the package facts
      package_facts:
        manager: auto
    - name: Enable service cron
      service:
        name: cron
        enabled: 'yes'
        state: started
      when:
        - '"cron" in ansible_facts.packages'
  when: ansible_os_family in ['Debian']        
  tags:
    - ws
    - sec
    - mob
    - service_cron_enabled_deb

- name: Enable service cron rpm
  block:
    - name: Ensure cron is installed
      package:
        name: cronie
        state: present
    - name: Gather the package facts
      package_facts:
        manager: auto
    - name: Enable service cron
      service:
        name: crond
        enabled: 'yes'
        state: started
      when:
        - '"crond" in ansible_facts.packages'
  when: ansible_os_family in ['RedHat', 'Rocky']
  tags:
    - ws
    - sec
    - mob
    - service_cron_enabled_rpm