- name: Ensure fqdn hostname @ensure_fqdn_hostname
  block:
    - name: Ensure fqdn hostname Get @ensure_fqdn_hostname
      changed_when: false
      command: hostname
      register: result
    - name: Ensure fqdn hostname Set @ensure_fqdn_hostname
      command: "hostnamectl set-hostname {{ansible_hostname}}.{{var_local_domain}}"
      when:
        - result.stdout_lines[0] is defined
        - '"." not in result.stdout_lines[0] or "localdomain" in result.stdout_lines[0]'
    - name: Ensure fqdn hostname Hosts @ensure_fqdn_hostname
      lineinfile:
        path: /etc/hosts
        regexp: "^127.0.1.1"
        line: "127.0.1.1\t{{ansible_hostname}}.{{var_local_domain}} {{ansible_hostname}}"
  tags:
    - ws
    - ensure_fqdn_hostname