- name: Set environment variables
  block:
    - name: Set environment variables Proxy
      blockinfile:
        dest: /etc/profile.d/set-env.sh
        create: yes
        mode: a+x
        marker_begin: BEGIN_PROXY
        marker_end: END_PROXY
        block: |
          export http_proxy="{{var_proxy_server}}"
          export https_proxy="{{var_proxy_server}}"
          export no_proxy="{{var_no_proxy}}"
      when: var_proxy_server|length > 0
    - name: Set environment variables No proxy
      blockinfile:
        dest: /etc/profile.d/set-env.sh
        create: yes
        mode: a+x
        marker_begin: BEGIN_PROXY
        marker_end: END_PROXY
        block: ""
      when: var_proxy_server|length == 0
    - name: Set environment variables Proxy
      blockinfile:
        dest: /etc/profile.d/set-env.sh
        create: yes
        mode: a+x
        marker_begin: BEGIN_OTHER
        marker_end: END_OTHER
        block: |
          export GVFS_DISABLE_FUSE=1
  when: 
  tags:
    - ws
    - set_environment_variables