- name: Ensure rc.local bash @ensure_rc_local_bash
  block:
    - name: Ensure rc.local bash X @ensure_rc_local_bash
      changed_when: false
      file:
        path: /etc/rc.local
        mode: a+x
        state: touch
    - name: Ensure rc.local bash Shell @ensure_rc_local_bash
      lineinfile:
        dest: /etc/rc.local
        regexp: '^#!\/bin\/bash'
        line: "#!/bin/bash"
        create: true
        insertbefore: BOF
  tags:
    - ws
    - ensure_rc_local_bash
