- name: Set external repo Debian
  ignore_errors: true
  template:
    src: sources.list.{{ansible_lsb.codename}}.ext.j2
    dest: /etc/apt/sources.list
    mode: '0644'
  notify: Apt update cache
  when: var_installation_type != "workstation"
  tags:
    - mob
    - set_external_repo