- name: Set local repo Debian
  ignore_errors: true
  template:
    src: sources.list.{{ansible_lsb.codename}}.loc.j2
    dest: /etc/apt/sources.list
    mode: '0644'
  notify: Apt update cache
  when: var_internal_ansible_ip
  tags:
    - ws
    - sec
    - mob
    - always
    - set_local_repo
