- name: Ensure kernel modules are disabled
  block:
    - name: Ensure kernel modules are disabled deb
      template:
        src: 50-blacklist.conf.j2
        dest: /etc/modprobe.d/50-blacklist.conf
      when: ansible_os_family in ['Debian']      
      notify:
        - Depmod
        - Update initramfs
    - name: Ensure kernel modules are disabled rpm
      template:
        src: 50-blacklist.conf.j2
        dest: /etc/modprobe.d/50-blacklist.conf
      when: ansible_os_family in ['RedHat', 'Rocky', 'RED']
      notify:
        - Dracut update        
  tags:
    - ws
    - sec
    - kernel_modules_are_disabled