- name: Ensure kernel modules are disabled
  block:
    - name: Ensure kernel modules are disabled deb
      template:
        src: 50-blacklist.conf.j2
        dest: /etc/modprobe.d/50-blacklist.conf
      when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"      
      notify:
        - Depmod
        - Update initramfs
    - name: Ensure kernel modules are disabled rpm
      template:
        src: 50-blacklist.conf.j2
        dest: /etc/modprobe.d/50-blacklist.conf
      when: ansible_distribution == "CentOS" or ansible_distribution == "OracleLinux"
      notify:
        - Dracut update        
  tags:
    - ws
    - sec
    - kernel_modules_are_disabled