- name: Install openscap client dependencies focal @install_openscap_dependencies_focal
  ignore_errors: "{{ansible_check_mode}}"
  package:
    name:
      - libopenscap8
    state: present
  ignore_errors: yes
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int == 20
  tags:
    - ws
    - sec
    - install_openscap_dependencies_focal

- name: Install openscap client dependencies bullseye @install_openscap_dependencies_bullseye
  ignore_errors: "{{ansible_check_mode}}"
  package:
    name: openscap
    state: present
  when: ansible_distribution == "Debian" and ansible_distribution_major_version|int == 11
  tags:
    - ws
    - sec
    - install_openscap_dependencies_bullseye

- name: OpenSCAP CVE vulnerability scan ubuntu @oscap_oval_eval_ubuntu
  ignore_errors: "{{ansible_check_mode}}"
  block:
    - name: OpenSCAP CVE vulnerability scan ubuntu Get_url @oscap_oval_eval_ubuntu
      changed_when: false
      get_url:
        url: https://security-metadata.canonical.com/oval/com.ubuntu.{{ansible_lsb.codename}}.usn.oval.xml.bz2
        dest: "/home/{{var_ansible_username}}/"
        mode: go+r
    - name: OpenSCAP CVE vulnerability scan ubuntu Remove @oscap_oval_eval_ubuntu
      changed_when: false
      file:
        name: "/home/{{var_ansible_username}}/com.ubuntu.{{ansible_lsb.codename}}.usn.oval.xml"
        state: absent
    - name: OpenSCAP CVE vulnerability scan ubuntu Bunzip2 @oscap_oval_eval_ubuntu
      changed_when: false
      command: "bunzip2 -k /home/{{var_ansible_username}}/com.ubuntu.{{ansible_lsb.codename}}.usn.oval.xml.bz2"
    - name: OpenSCAP CVE vulnerability scan ubuntu Scan @oscap_oval_eval_ubuntu
      check_mode: no
      shell: >-
        oscap oval eval --skip-valid  /home/{{var_ansible_username}}/com.ubuntu.{{ansible_lsb.codename}}.usn.oval.xml |
        grep true | grep -o "[0-9]*" | sort
      register: cve
      changed_when: false
      failed_when: false
    - name: OpenSCAP CVE vulnerability scan ubuntu Check cve @oscap_oval_eval_ubuntu
      changed_when: true
      failed_when: false
      debug:
        msg: "{{item}}"
      with_items: "{{cve.stdout_lines}}"
      when: item not in var_cve_whitelist
  when: ansible_distribution == "Ubuntu"
  tags:
    - ws
    - oscap_oval_eval_ubuntu

- name: OpenSCAP CVE vulnerability scan debian @oscap_oval_eval_debian
  ignore_errors: "{{ansible_check_mode}}"
  block:
    - name: OpenSCAP CVE vulnerability scan debian Copy @oscap_oval_eval_debian
      changed_when: false
      get_url:
        url: https://www.debian.org/security/oval/oval-definitions-{{ansible_lsb.codename}}.xml
        dest: "/home/{{var_ansible_username}}/"
        mode: go+r
    - name: OpenSCAP CVE vulnerability scan debian Scan @oscap_oval_eval_debian
      check_mode: no
      shell: 'oscap oval eval --skip-valid /home/{{var_ansible_username}}/oval-definitions-{{ansible_lsb.codename}}.xml | grep true | grep -o "[0-9]*" | sort'
      register: cve
      changed_when: false
      failed_when: false
    - name: OpenSCAP CVE vulnerability scan debian Check cve @oscap_oval_eval_debian
      changed_when: true
      failed_when: false
      debug:
        msg: "{{item}}"
      with_items: "{{cve.stdout_lines}}"
      when: item not in var_cve_whitelist
  when: ansible_distribution == "Debian"
  tags:
    - ws
    - oscap_oval_eval_debian
