- name: Update grub
  block:
    - name:
      command: update-grub
      when: ansible_os_family in ['Debian']
    - name:
      command: grub2-mkconfig --output /boot/grub2/grub.cfg    
      when: ansible_os_family in ['RedHat', 'Rocky', 'RED']

- name: Rc-local restarted
  changed_when: false
  failed_when: false
  service:
    name: rc-local
    enabled: 'yes'
    state: restarted