- name: Update grub
  command: update-grub

- name: Grub2 mkconfig
  command: grub2-mkconfig --output /boot/grub2/grub.cfg

- name: Rc-local restarted
  changed_when: false
  failed_when: false
  service:
    name: rc-local
    enabled: 'yes'
    state: restarted