- name: Sssd packages are present @sssd_packages_are_present
  block:
    - name: Sssd packages are present Common @sssd_packages_are_present
      package:
        name:
          - realmd
          - sssd
          - sssd-tools
          - sssd-kcm
          - adcli
          - keyutils
        state: present
    - name: Sssd packages are present Specific @sssd_packages_are_present
      package:
        name: "{{['libnss-sss', 'libpam-sss'] if ansible_pkg_mgr == 'apt' else 'sssd-client'}}"
        state: present
  tags:
    - ws
    - sssd_packages_are_present

- name: Sssd service Enabled @sssd_service_enabled
  ignore_errors: "{{ansible_check_mode}}"
  service:
    name: sssd
    enabled: yes
  tags:
    - ws
    - sssd_service_enabled

- name: Sssd-kcm service Enabled @sssd_service_enabled
  ignore_errors: "{{ansible_check_mode}}"
  service:
    name: sssd-kcm
    enabled: yes
  tags:
    - ws
    - sssd_kcm_service_enabled    

- name: Root copy realm wrapper @copy_realm_wrapper
  template:
    src: realm.sh.j2
    dest: /root/realm.sh
    mode: 0700
  tags:
    - ws
    - copy_realm_wrapper

- name: Copy realm.conf @copy_realmd_conf
  template:
    src: realmd.conf.j2
    dest: /etc/realmd.conf
  tags:
    - ws
    - copy_realmd_conf

- name: Root copy sssd.conf @root_copy_sssd_conf
  template:
    src: sssd.conf.j2
    dest: /root/sssd.conf
    mode: 0600
  tags:
    - ws
    - root_copy_sssd_conf

- name: Check and fix existing sssd.conf @check_existing_sssd_conf
  block:
    - name: Check and fix existing sssd.conf Stat file @check_existing_sssd_conf
      stat:
        path: /etc/sssd/sssd.conf
      register: stat_result
    - name: Check and fix existing sssd.conf Check line @check_existing_sssd_conf
      check_mode: true
      lineinfile:
        path: /etc/sssd/sssd.conf
        line: "domains = {{var_local_domain}}"
        state: present
      register: line_result
      when: stat_result.stat.exists
    - name: Check and fix existing sssd.conf Copy template @check_existing_sssd_conf
      template:
        src: sssd.conf.j2
        dest: /etc/sssd/sssd.conf
        mode: 0600
      notify: Sssd restarted
      when: stat_result.stat.exists and line_result is not changed
  tags:
    - ws
    - sec
    - check_existing_sssd_conf

- name: Pam mkhomedir @pam_mkhomedir
  block:
    - name: Pam mkhomedir deb @pam_mkhomedir
      lineinfile:
        dest: /etc/pam.d/common-session
        regexp: ^\s*session\s*optional\s*pam_mkhomedir.so
        line: session optional pam_mkhomedir.so skel=/etc/skel umask=0077
        insertbefore: ^\s*session\s*required\s*pam_unix.so
      when: ansible_pkg_mgr == 'apt'
    - name: Pam mkhomedir rpm @pam_mkhomedir
      package:
        name: authselect-compat
        state: present
      when: ansible_pkg_mgr == 'dnf'
    - name: Pam mkhomedir rpm @pam_mkhomedir
      shell: authconfig --enablemkhomedir --update
      when: ansible_pkg_mgr == 'dnf'
  tags:
    - ws
    - pam_mkhomedir

