var_backgroung_image: example-1920x1080.jpg

var_hidden_apps:
  - "rhythmbox.desktop"
  - "transmission-gtk.desktop"
var_visible_apps:
  - "libreoffice-base.desktop"
  - "libreoffice-math.desktop"

var_favorite_apps:
  - "chromium-browser.desktop"
  - "libreoffice-calc.desktop"
  - "libreoffice-impress.desktop"

var_remove_share_apps_desktop:
  - org.gnome.Mines.desktop
  - org.gnome.Mahjongg.desktop
  - sol.desktop

# active, urgency, expire-time ms, summary, body
var_notification_list:
  audit:         [true, "normal", 5000, "Warning", "The computer is regularly checked and tuned"]
  apt:           [false, "normal", 5000, "Warning", "Serching for updates"]
  scap:          [false, "low", 5000, "Warning", "Security scanning"]
  utmost-report: [true, "low", 5000, "Informational message", "Regular computer scan completed"]
  reboot:        [false, "critical", 0, "Warning", "Please restart your computer"]
