var_backgroung_image: example-1920x1080.jpg

var_hidden_apps:
  - "rhythmbox.desktop"
  - "transmission-gtk.desktop"
var_visible_apps:
  - "libreoffice-base.desktop"
  - "libreoffice-math.desktop"

var_favorite_apps:
  - "chromium-browser.desktop"
  - "libreoffice-calc.desktop"
  - "libreoffice-impress.desktop"

var_remove_share_apps_desktop:
  - org.gnome.Mines.desktop
  - org.gnome.Mahjongg.desktop
  - sol.desktop

# active, role, urgency, expire-time ms, summary, body
var_notification_list:
  - [true, "audit", "normal", 5000, "Warning", "The computer is regularly checked and tuned"]
  - [false, "apt", "normal", 5000, "Warning", "Serching for updates"]
  - [false, "apt", "critical", 3600000, "Warning", "Do not turn off the computer until the update operation is completed"]
  - [false, "scap", "low", 5000, "Warning", "Security scanning"]
  - [true, "utmost-report", "low", 0, "Informational message", "Update operation completed"]
  - [false, "utmost-report", "low", 5000, "Informational message", "Regular computer scan completed"]
  - [false, "utmost-report", "critical", 0, "Warning", "Please restart your computer"]
