
- name: Copy applications desktop files @copy_apps_desktop_files
  ignore_errors: "{{ansible_check_mode}}"
  copy:
    src: "{{item}}"
    dest: /usr/share/applications/
    mode: go+r
  with_fileglob:
    - "{{playbook_dir}}/inventories/all/files/desktop/applications/*"
  tags:
    - ws
    - copy_apps_desktop_files
