- name: Notify all users @notify_all_users
  ignore_errors: yes
  block:
    - name: Notify all users List @notify_all_users
      changed_when: false
      find:
        paths: /run/user/
        recurse: no
        file_type: directory
      register: runuserdirs
    - name: Notify all users Send @notify_all_users
      changed_when: false
      failed_when: false
      command: >
        sudo -u #{{item.path|basename}} DBUS_SESSION_BUS_ADDRESS='unix:path={{item.path}}/bus'
        notify-send -u '{{var_notification_list[role_name][1]}}' -t '{{var_notification_list[role_name][2]}}'
        '{{var_notification_list[role_name][3]}}' '{{var_notification_list[role_name][4]}}'
      when: (var_notification_list[role_name] is defined) and var_notification_list[role_name][0]
      with_items:
        - "{{runuserdirs.files}}"
  tags:
    - ws
    - notify_all_users

