- name: Copy notify send all script @notify_send_all
  ignore_errors: "{{ansible_check_mode}}"
  copy:
    dest: /usr/local/bin/notify-send-all.sh
    mode: a+rx
    content: |
      #!/bin/bash
      function notify-send() {
          local display=":$(ls /tmp/.X11-unix/* | sed 's#/tmp/.X11-unix/X##' | head -n 1)"
          local user=$(who | grep '('$display')' | awk '{print $1}' | head -n 1)
          local uid=$(id -u $user)
          local dbusaddr=$(ps -u $user e | grep -Eo 'dbus-daemon.*ADDRESS=unix:abstract=/tmp/dbus-[A-Za-z0-9]{10}' | tail -c35)
          sudo -u $user DISPLAY=$display DBUS_SESSION_BUS_ADDRESS=$dbusaddr notify-send "$@"
      }
      { sleep 900; notify-send "$@"; } &
  tags:
    - ws
    - notify_send_all
