- name: Notify all users @notify_all_users
  ignore_errors: yes
  block:
    - name: Notify all users List @notify_all_users
      changed_when: false
      find:
        paths: /run/user/
        recurse: no
        file_type: directory
      register: runuserdirs
    - name: Notify all users Send @notify_all_users
      changed_when: false
      command: >
        sudo -u #{{item.0.path|basename}} DBUS_SESSION_BUS_ADDRESS='unix:path={{item.0.path}}/bus'
        notify-send -u '{{item.3}}' -t '{{item.4}}' '{{item.5}}' '{{item.6}}'
      when: item.1 and item.2 == role_name
      with_nested:
        - "{{runuserdirs.files}}"
        - "{{var_notification_list}}"
  tags:
    - ws
    - notify_all_users

