- name: Set desktop background @set_desktop_background
  ignore_errors: "{{ansible_check_mode}}"
  block:
    - name: Set desktop background Copy file @set_desktop_background
      copy:
        src: "{{playbook_dir}}/inventories/all/files/desktop/images/{{var_backgroung_image}}"
        dest: /usr/share/backgrounds/
        mode: a+r
    - name: Set desktop background Copy to profile @set_desktop_background
      copy:
        dest: /etc/profile.d/set-desktop-background.sh
        mode: a+x
        content: |
          #!/bin/bash
          #
          gsettings set org.gnome.desktop.background picture-uri file:////usr/share/backgrounds/{{var_backgroung_image}}
  tags:
    - ws
    - set_desktop_background
