# use Hidden=true to hide

- name: Users desktop symlinks @users_desktop_symlinks
  block:
    - name: Users desktop symlinks Find @users_desktop_symlinks
      find:
        paths: /home
        recurse: yes
        depth: 2
        patterns: "Desktop"
        file_type: any
      register: desktopdirs
    - name: Users desktop symlinks File @users_desktop_symlinks
      file:
        src: "/usr/share/applications/{{item.0}}"
        dest: "{{item.1.path}}/{{item.0}}"
        force: true
        state: link
      with_nested:
        - "{{var_desktop_symlinks}}"
        - "{{desktopdirs.files}}"
  rescue:
    - name: Failed to copy users desktop files
      debug:
        msg: "Failed to copy users desktop files"
  tags:
    - ws
    - users_desktop_symlinks

- name: Users desktop files remove Find home @users_desktop_files
  ignore_errors: "{{ansible_check_mode}}"
  block:
    - name: Users desktop files remove Find home @users_desktop_files
      find:
        paths: /home
        recurse: yes
        depth: 2
        patterns: "Desktop"
        file_type: any
      register: desktopdirs
    - name: Users desktop files remove Copy @users_desktop_files
      file:
        path: "{{item.1.path}}/{{item.0}}"
        state: absent
      with_nested:
        - "{{var_desktop_files_remove}}"
        - "{{desktopdirs.files}}"
  rescue:
    - name: Failed to remove users desktop files
      debug:
        msg: "Failed to remove users desktop files"
  tags:
    - ws
    - users_desktop_files_remove