- name: Local admin password solution @local_admin_password_solution
  ignore_errors: "{{ansible_check_mode}}"
  block:
    - name: Local admin password solution Local users with passwords @local_admin_password_solution
      command: awk -F ':' '{ if(substr($2, 1, 1) == "$") {print $1} }' /etc/shadow
      register: result
    - name: Local admin password solution Check sudo rights @local_admin_password_solution
      shell: "sudo -l -U {{item}} | grep -o ALL"
      with_items: "{{result.stdout_lines}}"
      register: admin_with_passwd
  when: var_installation_type == "admin-workstation"
  tags:
    - ws
    - sec
    - local_admin_password_solution