- name: Disable service ufw @service_ufw_disabled
  ignore_errors: "{{ansible_check_mode}}"
  package:
    name: ufw
    state: absent
  tags:
    - ws
    - service_ufw_disabled

- name: Enable service firewalld @service_firewalld_enabled
  ignore_errors: "{{ansible_check_mode}}"
  block:
    - name: Gather the package facts @service_firewalld_enabled
      package_facts:
        manager: auto
    - name: Enable service firewalld Present @service_firewalld_enabled
      package:
        name: firewalld
        state: present
    - name: Enable service firewalld @service_firewalld_enabled
      service:
        name: firewalld
        enabled: 'yes'
        state: started
      when:
        - '"firewalld" in ansible_facts.packages'
  tags:
    - ws
    - service_firewalld_enabled

- name: Set initial firewalld rules @initial_firewalld_rules
  ignore_errors: "{{ansible_check_mode}}"
  block:
    - name: Set initial firewalld rules Clear other zones @initial_firewalld_rules
      copy:
        dest: "/etc/firewalld/zones/{{item}}.xml"
        content: |
          <?xml version="1.0" encoding="utf-8"?>
          <zone>
            <short>{{item}}</short>
          </zone>
      with_items:
        - block
        - drop
        - external
        - home
        - internal
        - public
      notify: Firewalld restarted
    - name: Set initial firewalld rules Trusted zone @initial_firewalld_rules
      template:
        src: inventories/all/files/firewall/trusted.xml.j2
        dest: "/etc/firewalld/zones/trusted.xml"
      when: var_installation_type == 'workstation' or var_installation_type == 'distribution-point'
      notify: Firewalld restarted
    - name: Set initial firewalld rules DMZ zone @initial_firewalld_rules
      template:
        src: inventories/all/files/firewall/dmz.xml.j2
        dest: "/etc/firewalld/zones/dmz.xml"
      when: var_installation_type == 'workstation' or var_installation_type == 'distribution-point'
      notify: Firewalld restarted
    - name: Set initial firewalld rules Work zone @initial_firewalld_rules
      template:
        src: inventories/all/files/firewall/work.xml.j2
        dest: "/etc/firewalld/zones/work.xml"
      when: var_installation_type == 'workstation' or var_installation_type == 'distribution-point'
      notify: Firewalld restarted
    - name: Set initial firewalld rules LogDenied @initial_firewalld_rules
      lineinfile:
        path: /etc/firewalld/firewalld.conf
        # line: LogDenied=unicast
        line: LogDenied=off
        regexp: ^\s*LogDenied
        state: present
      notify: Firewalld restarted
    - name: Set initial firewalld rules DefaultZone @initial_firewalld_rules
      lineinfile:
        path: /etc/firewalld/firewalld.conf
        line: DefaultZone=work
        regexp: ^\s*DefaultZone
        state: present
      when: var_installation_type == 'workstation' or var_installation_type == 'distribution-point'
      notify: Firewalld restarted
    - name: Set initial firewalld rules DefaultZone @initial_firewalld_rules
      lineinfile:
        path: /etc/firewalld/firewalld.conf
        line: DefaultZone=public
        regexp: ^\s*DefaultZone
        state: present
      when: var_installation_type == 'mobile-device' or var_installation_type == 'flash-drive'
      notify: Firewalld restarted
  tags:
    - ws
    - sec
    - mob
    - initial_firewalld_rules

- name: Drop ougoing traffic @drop_outgoing_traffic
  ignore_errors: "{{ansible_check_mode}}"
  block:
    - name: Drop ougoing traffic Service started @drop_outgoing_traffic
      service:
        name: firewalld
        state: started
    - name: Drop ougoing traffic Ftp @drop_outgoing_traffic
      changed_when: false
      failed_when: no
      shell: firewall-cmd --permanent --direct --add-rule ipv4 filter OUTPUT 0 -p tcp -m tcp --dport=21 -j DROP
    - name: Drop ougoing traffic Telnet @drop_outgoing_traffic
      changed_when: false
      failed_when: no
      shell: firewall-cmd --permanent --direct --add-rule ipv4 filter OUTPUT 0 -p tcp -m tcp --dport=23 -j DROP
  tags:
    - mob
    - drop_outgoing_traffic

- name: Verify firewalld rules @verify_firewalld_rules
  ignore_errors: "{{ansible_check_mode}}"
  block:
    - name: Verify firewalld rules Get services @verify_firewalld_rules
      shell: "firewall-cmd --list-all-zones | grep 'services: [a-z]' | awk '{print $2}'"
      register: items
      failed_when: no
      check_mode: no
      changed_when: false
    - name: Verify firewalld rules Check services @verify_firewalld_rules
      changed_when: true
      debug:
        msg: "{{item}}"
      with_items: "{{items.stdout.split()}}"
      when: item not in var_fw_services_whitelist
    - name: Verify firewalld Get ports @verify_firewalld_rules
      shell: 'firewall-cmd --list-all-zones | grep -Eo "[0-9]{1,5}\/(tcp|udp)"'
      register: items
      failed_when: no
      check_mode: no
      changed_when: false
    - name: Verify firewalld rules Check ports @verify_firewalld_rules
      changed_when: true
      debug:
        msg: "{{item}}"
      with_items: "{{items.stdout.split()}}"
      when: item not in var_fw_ports_whitelist
    - name: Verify firewalld rules Get active zones @verify_firewalld_rules
      shell: "firewall-cmd --get-active-zones | grep '^[a-z]' | awk '{print $1}'"
      register: items
      failed_when: no
      check_mode: no
      changed_when: false
    - name: Verify firewalld rules Check active zones @verify_firewalld_rules
      changed_when: true
      debug:
        msg: "{{item}}"
      with_items: "{{items.stdout.split()}}"
      when: item not in var_fw_active_zones
    - name: Verify firewalld rules Get default zone @verify_firewalld_rules
      shell: "firewall-cmd --get-default-zone"
      register: items
      failed_when: no
      check_mode: no
      changed_when: false
    - name: Verify firewalld rules Check default zone @verify_firewalld_rules
      changed_when: true
      debug:
        msg: "{{item}}"
      with_items: "{{items.stdout.split()}}"
      when: item not in var_fw_default_zone
    - name: Verify firewalld rules Get target @verify_firewalld_rules
      shell: "firewall-cmd --zone={{var_fw_default_zone[0]}} --permanent --get-target"
      register: items
      failed_when: no
      check_mode: no
      changed_when: false
    - name: Verify firewalld rules Check target @verify_firewalld_rules
      changed_when: true
      debug:
        msg: "{{item}}"
      with_items: "{{items.stdout.split()}}"
      when: item not in var_fw_target
  tags:
    - ws
    - sec
    - verify_firewalld_rules

- name: Set iptables persistent @set_iptables_persistent
  ignore_errors: "{{ansible_check_mode}}"
  block:
    - name: Set iptables persistent Present @set_iptables_persistent
      package:
        name:
          - iptables-persistent
          - netfilter-persistent
        state: present
      ignore_errors: yes
      register: package_result
    - name: Set iptables persistent V4 @set_iptables_persistent
      copy:
        dest: /etc/iptables/rules.v4
        content: |
          *filter
          :INPUT DROP [0:0]
          :FORWARD DROP [0:0]
          :OUTPUT ACCEPT [0:0]
          COMMIT
      when: not package_result.failed
    - name: Set iptables persistent V6 @set_iptables_persistent
      copy:
        dest: /etc/iptables/rules.v6
        content: |
          *filter
          :INPUT DROP [0:0]
          :FORWARD DROP [0:0]
          :OUTPUT ACCEPT [0:0]
          COMMIT
      when: not package_result.failed
  tags:
    - ws
    - sec
    - mob
    - set_iptables_persistent

- name: Disable netfilter-persistent # temporary workaround @check_listening_ports
  ignore_errors: "{{ansible_check_mode}}"
  service:
    name: netfilter-persistent
    enabled: no
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int == 22

- name: Check listening ports @check_listening_ports
  ignore_errors: "{{ansible_check_mode}}"
  block:
    - name: Check listening ports Get @check_listening_ports
      shell: ss -pnl | awk '{print $1,$5}'
      failed_when: false
      check_mode: no
      register: result
      changed_when: false
    - name: Check listening ports Check @check_listening_ports
      changed_when: true
      failed_when: false
      debug:
        msg: "{{item}}"
      with_items: "{{result.stdout_lines}}"
      when: item in var_listening_ports_blacklist
  tags:
    - ws
    - sec
    - check_listening_ports
