- name: Networking restarted
  failed_when: false
  service:
    name: networking
    state: restarted

- name: Apt update cache
  apt:
    update_cache: yes

- name: Cron restarted
  service:
    name: cron
    state: restarted
  tags:
    - ws
    - cron_restarted
