- name: Networking restarted
  failed_when: false
  service:
    name: networking
    state: restarted

- name: Apt update cache
  failed_when: false
  apt:
    update_cache: yes

- name: Cron restarted
  ignore_errors: "{{ansible_check_mode}}"
  service:
    name: cron
    state: restarted
