var_auditd_exceptions: |
  -a never,exit -S all -F exe=/usr/lib/chromium/chromium
  -a never,exit -S all -F exe=/lib/systemd/systemd-journald
  -a never,exit -S all -F exe=/usr/sbin/cupsd
  -a never,exit -S all -F path=/bin/sleep
  -a never,exit -S all -F path=/sbin/killall5
  -a never,exit -S all -F dir=/dev/shm/
  -a never,exclude -F msgtype=EOE
  -a never,exclude -F msgtype=PROCTITLE
  -a never,exclude -F msgtype=CWD
var_auditd_rules_count: 120
var_logstash_server: logstash.example.test
var_rsyslog_filter: |
  :msg, contains, "SOME USELESS TEXT" stop
  :msg, contains, "SOME TEXT" @{{ var_dp_rsyslog_server }}
var_syslog_ng_filter: |
  destination d_null { file("/dev/null"); };
  filter f_remote { message('SOME TEXT'); };
  filter f_trash { message('pcieport') or message('cifs.upcall'); };
  log { source(s_src); filter(f_remote); destination(remote_syslog); };
  log { source(s_src); filter(f_trash); destination(d_null); flags(final); };

var_audit_keys:
  access: access
  audit: audit
  cert: cert
  connect: connect
  cron: cron
  etc: etc
  exec: exec
  firewall: firewall
  home: home
  identity: identity
  login: login
  media: media
  module: module
  mount: mount
  networking: networking
  pam: pam
  profile: profile
  selinux: selinux
  session: session
  setuid: setuid
  stat: stat
  sudo: sudo
  system: system
  time: time
  unlink: unlink
  unsuccess: unsuccess
