- name: Clamav onacc service
  template:
    src: clamav-onacc.service.j2
    dest: /usr/lib/systemd/system/clamav-onacc.service
    mode: u=rw,g=r,o=r  
  notify:
    - Systemctl daemon reload
    - Clamav onacc restarted
  tags:
    - ws
    - clamav_onacc_service