- name: Clamav onacc service
  template:
    src: clamav-onacc.service.j2
    dest: /usr/lib/systemd/system/clamav-onacc.service
    mode: u=rw,g=r,o=r
  notify:
    - Systemctl daemon reload
    - Clamav onacc restarted
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"    
  tags:
    - ws
    - clamav_onacc_service

- name: Clamav onacc enabled
  service:
    name: clamav-onacc
    enabled: yes
  ignore_errors: yes
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
  tags:
    - ws
    - clamav_onacc_enabled    