- name: Clamav onacc service @clamav_onacc_service
  ignore_errors: "{{ansible_check_mode}}"
  template:
    src: clamav-onacc.service.j2
    dest: /usr/lib/systemd/system/clamav-onacc.service
    mode: u=rw,g=r,o=r
  notify:
    - Systemctl daemon reload
    - Clamav onacc restarted
  when: ansible_os_family in ['Debian']
  tags:
    - ws
    - clamav_onacc_service

- name: Clamav onacc enabled @clamav_onacc_enabled
  ignore_errors: yes
  service:
    name: clamav-onacc
    enabled: yes
  when: ansible_os_family in ['Debian']
  tags:
    - ws
    - clamav_onacc_enabled
