- name: Clamav freshclam workaround # be careful @clamav_freshclam_workaround
  ignore_errors: "{{ansible_check_mode}}"
  block:
    - name: Clamav freshclam workaround Check files @clamav_freshclam_workaround
      stat:
        path: "/var/lib/clamav/main.cvd"
      register: result
    - name: Clamav freshclam workaround Rpm present @clamav_freshclam_workaround
      package:
        name:
          - rpm2cpio
        state: present
      when: not result.stat.exists
    - name: Clamav freshclam workaround Mkdir @clamav_freshclam_workaround
      file:
        path: /var/lib/clamav
        state: directory
        mode: 0755
      when: not result.stat.exists
    - name: Clamav freshclam workaround Download @clamav_freshclam_workaround
      get_url:
        url: "{{var_clamav_data_rpm_url}}"
        dest: /var/lib/clamav/
      when: not result.stat.exists
    - name: Clamav freshclam workaround Unpack @clamav_freshclam_workaround
      shell:
        cmd: "rpm2cpio /var/lib/clamav/{{var_clamav_data_rpm_url | basename}} | cpio -imd"
        chdir: "/"
      when: not result.stat.exists
    - name: Clamav freshclam workaround Remove rpm @clamav_freshclam_workaround
      file:
        path: "/var/lib/clamav/{{var_clamav_data_rpm_url | basename}}"
        state: absent
  when: ansible_os_family in var_debian_based_os
  tags:
    - ws
    - clamav_freshclam_workaround
