- name: Clamav latest @clamav_latest
  ignore_errors: "{{ansible_check_mode}}"
  package:
    name:
      - clamav
      - clamav-daemon
      - clamdscan
    state: latest
  when: ansible_os_family in ['Debian']
  tags:
    - ws
    - clamav_latest

- name: Clamav Set local mirror @clamav_set_mirror
  ignore_errors: "{{ansible_check_mode}}"
  replace:
    path: /etc/clamav/freshclam.conf
    regexp: ^(DatabaseMirror).*
    replace: '\1 {{var_clamav_server}}'
  notify: Clamav freshclam restarted
  when: ansible_os_family in ['Debian']
  tags:
    - ws
    - clamav_set_mirror

- name: Clamd on access scanning @clamad_on_access_scanning
  ignore_errors: "{{ansible_check_mode}}"
  blockinfile:
    dest: /etc/clamav/clamd.conf
    marker_begin: BEGIN_ONACCESS
    marker_end: END_ONACCESS
    insertafter: EOF
    block: |
      OnAccessIncludePath {{var_clamav_onacc_dir}}
      OnAccessPrevention yes
      OnAccessExcludeUname clamd
  notify: Clamav daemon started
  when: ansible_os_family in ['Debian']
  tags:
    - ws
    - clamad_on_access_scanning
