
- name: Set Access control table @set_access_control_table
  ignore_errors: "{{ansible_check_mode}}"
  block:
    - name: Set Access control table User @set_access_control_table
      blockinfile:
        dest: /etc/security/access.conf
        marker_begin: BEGIN_GROUPS
        marker_end: END_GROUPS
        block: |
          + : @{{var_local_admins_group}} : LOCAL
          + : @{{var_domain_admins_group}} : ALL
          + : @{{var_domain_users_group}} : {{var_domain_users_group_access}}
          - : ALL : ALL
        insertafter: #
      when: not var_admin_workstation
    - name: Set Access control table Admin @set_access_control_table
      blockinfile:
        dest: /etc/security/access.conf
        marker_begin: BEGIN_GROUPS
        marker_end: END_GROUPS
        block: |
          + : @{{var_local_admins_group}} : LOCAL
          + : @{{var_domain_users_group}} : {{var_domain_users_group_access}}
          - : ALL : ALL
        insertafter: #
      when: var_admin_workstation
  tags:
    - ws
    - sec
    - set_access_control_table
