- name: Ensure blacklist services are removed @remove_blacklist_services
  ignore_errors: "{{ansible_check_mode}}"
  package:
    name: "{{item}}"
    state: absent
  with_items: "{{var_services_blacklist}}"
  when: var_installation_type not in ["server", "distribution-point"]
  tags:
    - ws
    - sec
    - remove_blacklist_services
