- name: Ensure cdrom group is empty @ensure_cdrom_group_is_empty
  ignore_errors: "{{ansible_check_mode}}"
  block:
    - name: Ensure cdrom group is empty Grep @ensure_cdrom_group_is_empty
      shell: awk -F ':' '($1 == "cdrom") {print $4}' /etc/group | tr , "\n"
      check_mode: no
      register: items
      changed_when: items.stdout_lines|length > 0
    - name: Ensure floppy group is empty Remove @ensure_cdrom_group_is_empty
      shell: gpasswd -d {{item}} cdrom
      with_items: "{{items.stdout_lines}}"
      when: items.stdout_lines|length > 0
  tags:
    - ws
    - sec
    - ensure_cdrom_group_is_empty

- name: Ensure floppy group is empty @ensure_floppy_group_is_empty
  ignore_errors: "{{ansible_check_mode}}"
  block:
    - name: Ensure floppy group is empty Grep @ensure_floppy_group_is_empty
      shell: awk -F ':' '($1 == "floppy") {print $4}' /etc/group | tr , "\n"
      check_mode: no
      register: items
      changed_when: items.stdout_lines|length > 0
    - name: Ensure floppy group is empty Remove @ensure_floppy_group_is_empty
      shell: gpasswd -d {{item}} floppy
      with_items: "{{items.stdout_lines}}"
      when: items.stdout_lines|length > 0
  tags:
    - ws
    - sec
    - ensure_floppy_group_is_empty

- name: Ensure dialout group is empty @ensure_dialout_group_is_empty
  ignore_errors: "{{ansible_check_mode}}"
  block:
    - name: Ensure dialout group is empty @ensure_dialout_group_is_empty
      shell: awk -F ':' '($1 == "dialout") {print $4}' /etc/group | tr , "\n"
      check_mode: no
      register: items
      changed_when: items.stdout_lines|length > 0
    - debug:
        msg: "dialout group is not empty"
      with_items: "{{items.stdout_lines}}"
      when: items.stdout_lines|length > 0
  tags:
    - ws
    - sec
    - ensure_dialout_group_is_empty
