- name: Ensure cdrom group is empty
  block:
    - name: Ensure cdrom group is empty Grep
      command: awk -F ':' '($1 == "cdrom") {print $4}' /etc/group
      check_mode: no
      register: items
      changed_when: items.stdout_lines|length > 0
    - name: Ensure floppy group is empty Remove
      shell: gpasswd -d {{items.stdout_lines[0]}} cdrom
      when: items.stdout_lines|length > 0
  tags:
    - ws
    - sec
    - ensure_cdrom_group_is_empty

- name: Ensure floppy group is empty
  block:
    - name: Ensure floppy group is empty Grep
      command: awk -F ':' '($1 == "floppy") {print $4}' /etc/group
      check_mode: no
      register: items
      changed_when: items.stdout_lines|length > 0
    - name: Ensure floppy group is empty Remove
      shell: gpasswd -d {{items.stdout_lines[0]}} floppy
      when: items.stdout_lines|length > 0
  tags:
    - ws
    - sec
    - ensure_floppy_group_is_empty

- name: Ensure dialout group is empty
  block:
    - name: Ensure dialout group is empty
      command: awk -F ':' '($1 == "dialout") {print $4}' /etc/group
      check_mode: no
      register: items
      changed_when: items.stdout_lines|length > 0
    - debug:
        msg: "dialout group is not empty"
      when: items.stdout_lines|length > 0
  tags:
    - ws
    - sec
    - ensure_dialout_group_is_empty