- name: Set grub2 password @set_grub2_password
  ignore_errors: "{{ansible_check_mode}}"
  block:
    - name: Set grub2 password Hash focal @set_grub2_password
      blockinfile:
        dest: /etc/grub.d/07_password
        block: |
            cat << EOF
            set superusers="{{var_superusers}}"
            password_pbkdf2 "{{var_superusers}}" "{{var_password_pbkdf2}}"
            EOF
        create: true
      notify: Update grub
    - name: Set grub2 password for Begin @set_grub2_password
      lineinfile:
        dest: /etc/grub.d/10_linux
        line: 'CLASS="--class gnu-linux --class gnu --class os --unrestricted"'
        insertbefore: ^SUPPORTED_INITS=.*
        state: present
        mode: 0700
        create: true
      notify: Update grub
    - name: Set grub2 password for Recovery @set_grub2_password
      lineinfile:
        dest: /etc/grub.d/10_linux
        line: '    CLASS="--class gnu-linux --class gnu --class os"'
        insertafter: if \[ \"x\$\{GRUB_DISABLE_RECOVERY\}\" != \"xtrue\" \]; then
        state: present
        create: true
      notify: Update grub
    - name: Set grub2 password for Recovery end @set_grub2_password
      lineinfile:
        dest: /etc/grub.d/10_linux
        line: '    CLASS="--class gnu-linux --class gnu --class os --unrestricted"'
        insertafter: \"\$\{GRUB_CMDLINE_LINUX_RECOVERY\} \$\{GRUB_CMDLINE_LINUX\}\"
        state: present
        create: true
      notify: Update grub
  when: ansible_os_family in ['Debian']
  tags:
    - ws
    - sec
    - mob
    - set_grub2_password

- name: Set grub cmdline @set_grub_cmdline
  ignore_errors: "{{ansible_check_mode}}"
  replace:
    dest: /etc/default/grub
    regexp: '(GRUB_CMDLINE_LINUX_DEFAULT=.*quiet net.ifnames=0).*$'
    replace: '\1 audit=1 audit_backlog_limit=8192 splash"'
  notify: Update grub
  when: ansible_os_family in ['Debian']
  tags:
    - ws
    - sec
    - mob
    - set_grub_cmdline

- name: Set-unset unrestricted os @set_unset_unrestricted_os
  ignore_errors: "{{ansible_check_mode}}"
  block:
    - name: Set-unset unrestricted os Set @set_unset_unrestricted_os
      replace:
        path: /etc/grub.d/30_os-prober
        regexp: '(\-\-class os) \\'
        replace: '\1 --unrestricted \\'
      notify: Update grub
      when: var_unrestricted_os
    - name: Set-unset unrestricted os Unset @set_unset_unrestricted_os
      replace:
        path: /etc/grub.d/30_os-prober
        regexp: '\-\-unrestricted '
        replace: ''
      notify: Update grub
      when: not var_unrestricted_os
  when: ansible_os_family in ['Debian']
  tags:
    - ws
    - sec
    - mob
    - set_unset_unrestricted_os

