- name: Configure etc hosts access @configure_etc_hosts_access
  ignore_errors: "{{ansible_check_mode}}"
  block:
    - name: Configure etc hosts access Allow @configure_etc_hosts_access
      blockinfile:
        dest: /etc/hosts.allow
        mode: 0644
        owner: root
        group: root
        create: true
        content: |
          ALL: 127.0.0.1
          ALL: 192.168.0.0/16
          ALL: 10.0.0.0/8
    - name: Configure etc hosts access Deny @configure_etc_hosts_access
      blockinfile:
        dest: /etc/hosts.deny
        mode: 0644
        owner: root
        group: root
        create: true
        content: |
          ALL: ALL
  when:
  tags:
    - ws
    - sec
    - configure_etc_hosts_access
