- name: Check lpadmin group @check_lpadmin_group
  ignore_errors: "{{ansible_check_mode}}"
  check_mode: yes
  changed_when: false # workaround
  replace:
    dest: /etc/group
    regexp: "^({{'lpadmin' if ansible_os_family in var_debian_based_os else 'lp'}}:x:[0-9]*:[^,]*),.*"
    replace: \1
  tags:
    - ws
    - sec
    - check_lpadmin_group

- name: Ensure cups SystemGroup @ensure_cups_systemgroup
  ignore_errors: "{{ansible_check_mode}}"
  failed_when: false
  lineinfile:
    path: /etc/cups/cups-files.conf
    regexp: ^\s*SystemGroup\s
    line: "SystemGroup {{'lpadmin' if ansible_os_family in var_debian_based_os else 'sys root wheel printadmin'}}"
    state: present
  tags:
    - ws
    - sec
    - ensure_cups_systemgroup


