- name: Check lpadmin group deb
  check_mode: yes
  replace:
    dest: /etc/group
    regexp: ^(lpadmin:x:[0-9]*:[^,]*),.*
    replace: \1
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
  tags:
    - ws
    - sec
    - check_lpadmin_group

- name: Ensure cups SystemGroup
  lineinfile:
    path: /etc/cups/cups-files.conf
    regexp: ^\s*SystemGroup\s
    line: SystemGroup lpadmin
    state: present
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
  tags:
    - ws
    - sec
    - ensure_cups_systemgroup_deb

- name: Check lpadmin group rpm
  check_mode: yes
  replace:
    dest: /etc/group
    regexp: ^(lp:x:[0-9]*:[^,]*),.*
    replace: \1
  when: ansible_distribution == "CentOS" or ansible_distribution == "OracleLinux"
  tags:
    - ws
    - sec
    - check_lpadmin_group_rpm

- name: Ensure cups SystemGroup rpm
  lineinfile:
    path: /etc/cups/cups-files.conf
    regexp: ^\s*SystemGroup\s
    line: SystemGroup lp
    state: present
  when: ansible_distribution == "CentOS" or ansible_distribution == "OracleLinux"
  tags:
    - ws
    - sec
    - ensure_cups_systemgroup_rpm
