- name: Check lpadmin group
  check_mode: yes
  replace:
    dest: /etc/group
    regexp: "^({{'lpadmin' if ansible_os_family in ['Debian'] else 'lp'}}:x:[0-9]*:[^,]*),.*"
    replace: \1
  tags:
    - ws
    - sec
    - check_lpadmin_group

- name: Ensure cups SystemGroup
  lineinfile:
    path: /etc/cups/cups-files.conf
    regexp: ^\s*SystemGroup\s
    line: "SystemGroup {{'lpadmin' if ansible_os_family in ['Debian'] else 'sys root wheel printadmin'}}"
    state: present
  tags:
    - ws
    - sec
    - ensure_cups_systemgroup


