- name: Remove lines starting with + from /etc/passwd @no_legacy_plus_entries_etc_passwd
  ignore_errors: "{{ansible_check_mode}}"
  lineinfile:
    regexp: ^\+.*$
    state: absent
    path: /etc/passwd
  tags:
    - ws
    - sec
    - mob
    - no_legacy_plus_entries_etc_passwd

- name: Remove lines starting with + from /etc/shadow @no_legacy_plus_entries_etc_shadow
  ignore_errors: "{{ansible_check_mode}}"
  lineinfile:
    regexp: ^\+.*$
    state: absent
    path: /etc/shadow
  tags:
    - ws
    - sec
    - mob
    - no_legacy_plus_entries_etc_shadow

- name: Remove lines starting with + from /etc/group @no_legacy_plus_entries_etc_group
  ignore_errors: "{{ansible_check_mode}}"
  lineinfile:
    regexp: ^\+.*$
    state: absent
    path: /etc/group
  tags:
    - ws
    - sec
    - mob
    - no_legacy_plus_entries_etc_group
