- name: Direct root Logins Not Allowed @no_direct_root_logins
  ignore_errors: "{{ansible_check_mode}}"
  copy:
    dest: /etc/securetty
    content: ''
  tags:
    - ws
    - sec
    - no_direct_root_logins

- name: Restrict Virtual Console Root Logins @securetty_root_login_console_only
  ignore_errors: "{{ansible_check_mode}}"
  lineinfile:
    dest: /etc/securetty
    regexp: ^vc
    state: absent
  tags:
    - ws
    - sec
    - securetty_root_login_console_only
