- name: Set pwhistory in pam @conf_pam_pwhistory
  ignore_errors: "{{ansible_check_mode}}"
  lineinfile:
    dest: /etc/pam.d/common-password
    regexp: ^#?\s*password\s*required\s*pam_pwhistory.so
    line: password required pam_pwhistory.so remember=6 retry=3
    state: present
    create: true
  tags:
    - ws
    - sec
    - mob
    - conf_pam_pwhistory

- name: Set Password Minimum Age @accounts_minimum_age_login_defs
  ignore_errors: "{{ansible_check_mode}}"
  lineinfile:
    create: true
    dest: /etc/login.defs
    regexp: ^#?PASS_MIN_DAYS
    line: "PASS_MIN_DAYS {{var_password_min_days}}"
  tags:
    - ws
    - sec
    - mob
    - accounts_minimum_age_login_defs

- name: Set Password Maximum Age @accounts_maximum_age_login_defs
  ignore_errors: "{{ansible_check_mode}}"
  block:
    - name: Set Password Maximum Age @accounts_maximum_age_login_defs
      lineinfile:
        create: true
        dest: /etc/login.defs
        regexp: ^#?PASS_MAX_DAYS
        line: "PASS_MAX_DAYS {{var_password_max_days}}"
      when: var_installation_type == "workstation" or var_installation_type == "distribution-point"
    - name: Set Password Maximum Age @accounts_maximum_age_login_defs
      lineinfile:
        create: true
        dest: /etc/login.defs
        regexp: ^#?PASS_MAX_DAYS
        line: "PASS_MAX_DAYS {{var_password_max_days_mob}}"
      when: var_installation_type == "mobile-device"
  tags:
    - ws
    - sec
    - mob
    - accounts_maximum_age_login_defs

- name: Set Password Hashing Algorithm in /etc/login.defs @set_password_hashing_algorithm_logindefs
  ignore_errors: "{{ansible_check_mode}}"
  lineinfile:
    dest: /etc/login.defs
    regexp: ^#?ENCRYPT_METHOD
    line: ENCRYPT_METHOD SHA512
    state: present
    create: true
  tags:
    - ws
    - sec
    - mob
    - set_password_hashing_algorithm_logindefs

- name: Ensure PAM variables are set accordingly @pam_variables_set
  ignore_errors: "{{ansible_check_mode}}"
  block:
    - name: Ensure PAM variables are set accordingly minlen @pam_variables_set
      lineinfile:
        create: true
        dest: /etc/security/pwquality.conf
        regexp: ^#?\s*minlen
        line: "minlen = {{var_password_minlen}}"
    - name: Ensure PAM variables are set accordingly lcredit @pam_variables_set
      lineinfile:
        create: true
        dest: /etc/security/pwquality.conf
        regexp: ^#?\s*lcredit
        line: lcredit = -1
    - name: Ensure PAM variables are set accordingly dcredit @pam_variables_set
      lineinfile:
        create: true
        dest: /etc/security/pwquality.conf
        regexp: ^#?\s*dcredit
        line: dcredit = -1
    - name: Ensure PAM variables are set accordingly ucredit @pam_variables_set
      lineinfile:
        create: true
        dest: /etc/security/pwquality.conf
        regexp: ^#?\s*ucredit
        line: ucredit = -1
    - name: Ensure PAM variables are set accordingly ocredit @pam_variables_set
      lineinfile:
        create: true
        dest: /etc/security/pwquality.conf
        regexp: ^#?\s*ocredit
        line: ocredit = -1
  tags:
    - ws
    - sec
    - mob
    - pam_variables_set

- name: Set deny configuation of pam_tally in pam @deny_conf_pam_faillock
  ignore_errors: "{{ansible_check_mode}}"
  block:
    - name: Set deny configuation of pam_tally in pam Common-auth Stat @deny_conf_pam_faillock
      find:
        paths:
          - /usr/lib64/security
          - /usr/lib/x86_64-linux-gnu/security
        patterns: pam_failllock.so
      register: result
    - name: Set deny configuation of pam_tally in pam Common-auth Line @deny_conf_pam_faillock
      lineinfile:
        dest: /etc/pam.d/common-auth
        regexp: ^#?\s*auth\s*\[success=ignore default=die\]\s*pam_faillock.so
        line: auth [success=ignore default=die] pam_faillock.so per_user deny=10 unlock_time=300
        state: present
        create: true
      when: result.matched > 0
  tags:
    - ws
    - sec
    - mob
    - deny_conf_pam_faillock

- name: Ensure no pam gnome keyring @ensure_no_pam_gnome_keyring
  ignore_errors: "{{ansible_check_mode}}"
  lineinfile:
    dest: /etc/pam.d/common-auth
    regexp: pam_gnome_keyring.so
    state: absent
  tags:
    - ws
    - sec
    - ensure_no_pam_gnome_keyring
