- name: Remove execution bit @remove_execution_bit
  ignore_errors: "{{ansible_check_mode}}"
  file:
    path: "{{item}}"
    mode: go-rwx
  failed_when: false
  with_items: "{{var_remove_exec_bit}}"
  tags:
    - ws
    - sec
    - mob
    - remove_execution_bit
