
- name: Restrict Serial Port Root Logins @restrict_serial_port_logins
  ignore_errors: "{{ansible_check_mode}}"
  lineinfile:
    dest: /etc/securetty
    regexp: ttyS[0-9]
    state: absent
  tags:
    - ws
    - restrict_serial_port_logins
