
- name: Accounts root path no write @accounts_root_path_dirs_no_write
  ignore_errors: "{{ansible_check_mode}}"
  block:
    - name: Get root paths which are not symbolic links @accounts_root_path_dirs_no_write
      become: yes
      stat:
        path: '{{ item }}'
      changed_when: false
      failed_when: false
      register: root_paths
      with_items: '{{ ansible_env.PATH.split('':'') }}'
    - name: Disable writability to root directories @accounts_root_path_dirs_no_write
      file:
        path: '{{ item.item }}'
        mode: g-w,o-w
      with_items: '{{ root_paths.results }}'
      when:
        - root_paths.results is defined
        - item.stat.exists
        - not item.stat.islnk
  tags:
    - ws
    - sec
    - mob
    - accounts_root_path_dirs_no_write
