- name: Set sudoers default noexec @set_sudoers_default_noexec
  ignore_errors: "{{ansible_check_mode}}"
  lineinfile:
    path: /etc/sudoers
    create: true
    regexp: '^\s*Defaults\s*noexec'
    line: "Defaults noexec"
    state: present
    insertafter: ^\s*Defaults
  tags:
    - ws
    - sec
    - set_sudoers_default_noexec

- name: Set sudoers groups @set_sudoers_groups
  ignore_errors: "{{ansible_check_mode}}"
  block:
    - name: Set sudoers groups User @set_sudoers_groups
      blockinfile:
        dest: /etc/sudoers
        marker_begin: BEGIN_GROUPS
        marker_end: END_GROUPS
        block: |
          %{{var_local_admins_group}} ALL=(ALL) EXEC:ALL, PASSWD:ALL
          %{{var_domain_admins_group}} ALL=(ALL) EXEC:ALL, PASSWD:ALL
        insertafter: EOF
      when: not var_admin_workstation
    - name: Set sudoers groups Admin @set_sudoers_groups
      blockinfile:
        dest: /etc/sudoers
        marker_begin: BEGIN_GROUPS
        marker_end: END_GROUPS
        block: |
          %{{var_local_admins_group}} ALL=(ALL) EXEC:ALL, PASSWD:ALL
        insertafter: EOF
      when: var_admin_workstation
  tags:
    - ws
    - sec
    - set_sudoers_groups

- name: Check sudoers users @check_sudoers_users
  ignore_errors: "{{ansible_check_mode}}"
  block:
    - name: Check sudoers users Get groups @check_sudoers_users
      shell: awk '{print $1}' /etc/sudoers | grep "%" | cut -c 2- | xargs -I {} grep {} /etc/group
      failed_when: false
      check_mode: no
      register: result
      changed_when: false
    - name: Check sudoers users Whitelist compare @check_sudoers_users
      changed_when: true
      failed_when: false
      debug:
        msg: "{{item}}"
      with_items: "{{result.stdout_lines}}"
      when: item not in var_sudoers_groups_whitelist
  tags:
    - ws
    - sec
    - check_sudoers_users

- name: Remove lines containing NOPASSWD from sudoers files @sudo_remove_nopasswd
  ignore_errors: "{{ansible_check_mode}}"
  block:
    - name: Find /etc/sudoers.d/ files @sudo_remove_nopasswd
      find:
        paths:
          - /etc/sudoers.d/
      register: sudoers
    - name: Remove lines containing NOPASSWD @sudo_remove_nopasswd
      replace:
        regexp: '(^(?!#).*^(?!.*({{var_ansible_username}})).*[\s]+NOPASSWD[\s]*\:.*$)'
        replace: '# \g<1>'
        path: '{{ item.path }}'
        validate: /usr/sbin/visudo -cf %s
      with_items:
        - path: /etc/sudoers
        - '{{ sudoers.files }}'
  tags:
    - ws
    - sec
    - sudo_remove_nopasswd

- name: Ensure env_reset and timeout is enabled in /etc/sudoers @sudo_add_env_reset_and_timeout
  ignore_errors: "{{ansible_check_mode}}"
  lineinfile:
    path: /etc/sudoers
    regexp: ^[\s]*Defaults.*\benv_reset\b.*$
    line: Defaults env_reset, timestamp_timeout=0
    validate: /usr/sbin/visudo -cf %s
  tags:
    - ws
    - sec
    - sudo_add_env_reset_and_timeout

- name: Ensure use_pty is enabled in /etc/sudoers @sudo_add_use_pty
  ignore_errors: "{{ansible_check_mode}}"
  lineinfile:
    path: /etc/sudoers
    regexp: ^[\s]*Defaults.*\buse_pty\b.*$
    line: Defaults use_pty
    insertafter: Defaults
    validate: /usr/sbin/visudo -cf %s
  tags:
    - ws
    - sec
    - sudo_add_use_pty

- name: Ensure tty_tickets is enabled in /etc/sudoers @sudo_add_tty_tickets
  ignore_errors: "{{ansible_check_mode}}"
  lineinfile:
    path: /etc/sudoers
    regexp: ^[\s]*Defaults.*\btty_tickets\b.*$
    line: Defaults tty_tickets
    insertafter: Defaults
    validate: /usr/sbin/visudo -cf %s
  tags:
    - ws
    - sec
    - sudo_add_tty_tickets

- name: Enable logfile option with appropriate value in /etc/sudoers @sudo_custom_logfile
  ignore_errors: "{{ansible_check_mode}}"
  lineinfile:
    path: /etc/sudoers
    line: Defaults logfile={{ var_sudo_logfile }}
    validate: /usr/sbin/visudo -cf %s
  tags:
    - ws
    - sec
    - mob
    - sudo_custom_logfile
