- name: Ensure sysctl kernel.dmesg_restrict is set to 1 @sysctl_kernel_dmesg_restrict
  ignore_errors: "{{ansible_check_mode}}"
  sysctl:
    name: kernel.dmesg_restrict
    value: '1'
    state: present
    reload: true
    ignoreerrors: yes
  tags:
    - ws
    - sec
    - mob
    - sysctl_kernel_dmesg_restrict

- name: Ensure sysctl fs.suid_dumpable is set to 0 @sysctl_fs_suid_dumpable
  ignore_errors: "{{ansible_check_mode}}"
  sysctl:
    name: fs.suid_dumpable
    value: '0'
    state: present
    reload: true
    ignoreerrors: yes
  tags:
    - ws
    - sec
    - sysctl_fs_suid_dumpable

- name: Ensure sysctl kernel.randomize_va_space is set to 2 @sysctl_kernel_randomize_va_space
  ignore_errors: "{{ansible_check_mode}}"
  sysctl:
    name: kernel.randomize_va_space
    value: '2'
    state: present
    reload: true
    ignoreerrors: yes
  tags:
    - ws
    - sec
    - sysctl_kernel_randomize_va_space

- name: Ensure sysctl accept_source_route is set @sysctl_accept_source_route_0
  ignore_errors: "{{ansible_check_mode}}"
  block:
    - name: Ensure sysctl net.ipv4.conf.all.accept_source_route @sysctl_accept_source_route_0
      sysctl:
        name: net.ipv4.conf.all.accept_source_route
        value: 0
        state: present
        reload: true
        ignoreerrors: yes
    - name: Ensure sysctl net.ipv4.conf.default.accept_source_route @sysctl_accept_source_route_0
      sysctl:
        name: net.ipv4.conf.default.accept_source_route
        value: 0
        state: present
        reload: true
        ignoreerrors: yes
    - name: Ensure sysctl net.ipv6.conf.all.accept_source_route @sysctl_accept_source_route_0
      sysctl:
        name: net.ipv6.conf.all.accept_source_route
        value: 0
        state: present
        reload: true
        ignoreerrors: yes
    - name: Ensure sysctl net.ipv6.conf.default.accept_source_route @sysctl_accept_source_route_0
      sysctl:
        name: net.ipv6.conf.default.accept_source_route
        value: 0
        state: present
        reload: true
        ignoreerrors: yes
  tags:
    - ws
    - sec
    - sysctl_accept_source_route_0

- name: Ensure sysctl net.ipv4.icmp_echo_ignore_broadcasts is set @sysctl_net_ipv4_icmp_echo_ignore_broadcasts
  ignore_errors: "{{ansible_check_mode}}"
  sysctl:
    name: net.ipv4.icmp_echo_ignore_broadcasts
    value: 1
    state: present
    reload: true
    ignoreerrors: yes
  tags:
    - ws
    - sec
    - sysctl_net_ipv4_icmp_echo_ignore_broadcasts

- name: Ensure sysctl net.ipv4.icmp_ignore_bogus_error_responses is set @sysctl_net_ipv4_icmp_ignore_bogus_error_responses
  ignore_errors: "{{ansible_check_mode}}"
  sysctl:
    name: net.ipv4.icmp_ignore_bogus_error_responses
    value: 1
    state: present
    reload: true
    ignoreerrors: yes
  tags:
    - ws
    - sec
    - sysctl_net_ipv4_icmp_ignore_bogus_error_responses

- name: Ensure sysctl net.ipv4.conf.all.rp_filter is set @sysctl_net_ipv4_conf_all_rp_filter
  ignore_errors: "{{ansible_check_mode}}"
  sysctl:
    name: net.ipv4.conf.all.rp_filter
    value: 1
    state: present
    reload: true
    ignoreerrors: yes
  tags:
    - ws
    - sec
    - sysctl_net_ipv4_conf_all_rp_filter

- name: Ensure sysctl net.ipv4.tcp_syncookies is set @sysctl_net_ipv4_tcp_syncookies
  ignore_errors: "{{ansible_check_mode}}"
  sysctl:
    name: net.ipv4.tcp_syncookies
    value: 1
    state: present
    reload: true
    ignoreerrors: yes
  tags:
    - ws
    - sec
    - sysctl_net_ipv4_tcp_syncookies

- name: Ensure sysctl net ip forward is set to 0 @sysctl_disable_net_forward
  ignore_errors: "{{ansible_check_mode}}"
  block:
    - name: Ensure sysctl net ip forward is set to 0 ipv4 @sysctl_disable_net_forward
      sysctl:
        name: net.ipv4.ip_forward
        value: '0'
        state: present
        reload: true
        ignoreerrors: yes
    - name: Ensure sysctl net ip forward is set to 0 ipv6 @sysctl_disable_net_forward
      sysctl:
        name: net.ipv6.conf.all.forwarding
        value: '0'
        state: present
        reload: true
        ignoreerrors: yes
  tags:
    - ws
    - sec
    - mob
    - sysctl_disable_net_forward

- name: Logging martian packets @logging_martian_packets
  ignore_errors: "{{ansible_check_mode}}"
  block:
    - name: Logging martian packets All @logging_martian_packets
      sysctl:
        name: net.ipv4.conf.all.log_martians
        value: '1'
        reload: yes
        ignoreerrors: yes
    - name: Logging martian packets Default @logging_martian_packets
      sysctl:
        name: net.ipv4.conf.default.log_martians
        value: '1'
        reload: yes
        ignoreerrors: yes
  tags:
    - ws
    - sec
    - logging_martian_packets
