- name: Set user umask in the etc files @accounts_umask_etc
  ignore_errors: "{{ansible_check_mode}}"
  block:
    - name: Set user umask in /etc/profile @accounts_umask_etc
      lineinfile:
        dest: /etc/profile
        line: umask 027
        regexp: ^\s*umask.*
        state: present
        create: true
    - name: Set user umask in /etc/bash.bashrc @accounts_umask_etc
      lineinfile:
        dest: /etc/bash.bashrc
        line: umask 027
        regexp: ^\s*umask.*
        state: present
        create: true
  tags:
    - ws
    - sec
    - mob
    - accounts_umask_etc
