var_no_shell_pass: "yuhewae2Thie5buZ"
var_fqdn_sshserver: "ssh.example.test"

no_shell_pass: "{{var_no_shell_pass}}"
fqdn_sshserver: "{{var_fqdn_sshserver}}"

var_sleep_timeout: 2

var_remote_assistance_exec: >-
  pass=$((32767+$RANDOM));
  port=$((32767+$RANDOM));
  disp=$(echo $DISPLAY|grep -o ":[0-9]*");
  (x11vnc -repeat -notruecolor -bg {{var_view_only}} -nomodtweak -passwd $pass -rfbport $port -display $disp > /dev/null 2>&1 & echo $! > ~/.x11vncpid-$port);
  (sshpass -p {{no_shell_pass}} ssh -o StrictHostKeyChecking=no -N -R $port:localhost:$port no-shell@{{fqdn_sshserver}} & echo $! > ~/.sshpid-$port);
  sleep {{var_sleep_timeout}};
  if [[ -z $(cat ~/.sshpid-$port) ]];
  then zenity --info --text="No connection" --ok-label="Exit";
  else zenity --info --text="Connection has been established\nID=$port, PIN=$pass" --ok-label="Disconnect";
  fi;
  kill $(cat ~/.x11vncpid-$port); kill $(cat ~/.sshpid-$port);
  rm -f ~/.x11vncpid-$port; rm -f ~/.sshpid-$port

var_helpdesk_exec: >-
  output=$(zenity --forms --title="Remote assistance" --text="Connection" --separator="," --add-entry="ID" --add-password="PIN");
  port=$(cut -d "," -f1 <<< "$output"); pass=$(cut -d  "," -f2 <<< "$output");
  (sshpass -p {{no_shell_pass}} ssh -o StrictHostKeyChecking=no -N -L $port:localhost:$port no-shell@{{fqdn_sshserver}} & echo $! > ~/.sshpid-$port);
  sleep {{var_sleep_timeout}};
  if [[ -z $(cat ~/.sshpid-$port) ]];
  then zenity --info --text="No connection" --ok-label="Exit";
  fi;
  (echo $pass | vncpasswd -f > ~/.vncpasswd);
  vncviewer -passwd ~/.vncpasswd ::$port; rm -f ~/.vncpasswd;
  kill $(cat ~/.sshpid-$port);
  rm -f ~/.sshpid-$port
