- name: Create no-shell user @ra_create_no_shell_user
  ignore_errors: "{{ansible_check_mode}}"
  block:
    - name: Create no-shell user Useradd @ra_create_no_shell_user
      user:
        name: no-shell
        shell: /bin/false
        password: "{{ var_no_shell_pass | password_hash('sha512') }}"
        generate_ssh_key: yes
  when: var_installation_type == "distribution-point"
  tags:
    - dp
    - ra_create_no_shell_user

- name: Ensure openssh-server is installed @ra_openssh_server_is_started
  ignore_errors: "{{ansible_check_mode}}"
  block:
    - name: Ensure openssh-server is installed Package @ra_openssh_server_is_started
      package:
        name: openssh-server
        state: present
    - name: Ensure openssh-server is installed Started @ra_openssh_server_is_started
      service:
        name: sshd
        state: started
  when: var_installation_type == "distribution-point"
  tags:
    - dp
    - ra_openssh_server_is_started

- name: Ensure openssh-server permit open local @ra_openssh_server_permitopen
  ignore_errors: "{{ansible_check_mode}}"
  blockinfile:
    dest: /etc/ssh/sshd_config
    marker_begin: BEGIN_NO_SHELL
    marker_end: END_NO_SHELL
    block: |
      Match User no-shell
        X11Forwarding no
        PermitOpen localhost:* 127.0.0.1:*
        PermitTTY no
    insertafter: EOF
  when: var_installation_type == "distribution-point"
  tags:
    - dp
    - ra_openssh_server_permitopen