- name: Fapolicyd remove outdated files @fapolicyd_remove_outdated_rules
  ignore_errors: true
  block:
    - name: Fapolicyd remove outdated files Set default @fapolicyd_remove_outdated_rules
      set_fact:
        local_files:
          - 19-dummy.rules
    - name: Fapolicyd remove outdated files Set local @fapolicyd_remove_outdated_rules
      set_fact:
        local_files: "{{ local_files + [item | basename | replace('.j2', '') ] }}"
      with_fileglob:
        - "{{playbook_dir}}/roles/fapolicyd/templates/*"
    - name: Fapolicyd remove outdated files Set local ou @fapolicyd_remove_outdated_rules
      set_fact:
        local_files: "{{ local_files + [item | basename | replace('.j2', '') ] }}"
      with_fileglob:
        - "{{playbook_dir}}/inventories/ou/{{var_ou_guid}}/files/fapolicyd/*"
      when: ou_fapolicyd_dir.stat.exists
    - name: Fapolicyd remove outdated files Find @fapolicyd_remove_outdated_rules
      find:
        path: /etc/fapolicyd/rules.d/
        recurse: no
        file_type: file
      register: remote_files_path
    - name: Fapolicyd remove outdated files Set remote @fapolicyd_remove_outdated_rules
      set_fact:
        remote_files: "{{ remote_files | default([]) + [item.path | basename] }}"
      with_items: "{{remote_files_path.files}}"
    - name: Fapolicyd remove outdated files Remove @fapolicyd_remove_outdated_rules
      file:
        path: /etc/fapolicyd/rules.d/{{item}}
        state: absent
      with_items: "{{ remote_files | difference(local_files) }}"
      notify: Fapolicyd reload rules
  when:
    - var_fapolicyd_service is defined
    - var_fapolicyd_service
  tags:
    - ws
    - fapolicyd_remove_outdated_rules
