- name: Set fapolicyd MemoryMax @fapolicyd_memorymax
  ignore_errors: "{{ansible_check_mode}}"
  block:
    - name: Set fapolicyd MemoryMax @fapolicyd_memorymax
      lineinfile:
        create: true
        dest: /usr/lib/systemd/system/fapolicyd.service
        regexp: ^#?\s*MemoryMax
        line: MemoryMax=512M
        insertafter: \[Service\]
      register: result
    - name: Set fapolicyd MemoryMax Restart @fapolicyd_memorymax
      systemd:
        state: restarted
        daemon_reload: true
        name: fapolicyd
      when: result.changed
  tags:
    - ws
    - sec
    - fapolicyd_memorymax