- name: Ensure apparmor is active @apparmor_is_active
  ignore_errors: "{{ansible_check_mode}}"
  block:
    - name: Ensure apparmor is active Installed @apparmor_is_active
      package:
        name: apparmor
        state: present
    - name: Gather the package facts @apparmor_is_active
      package_facts:
        manager: auto
    - name: Ensure apparmor is active Service started @apparmor_is_active
      service:
        name: apparmor
        enabled: 'yes'
        state: started
      when:
        - '"apparmor" in ansible_facts.packages'
    - name: Ensure apparmor is active Profiled @apparmor_is_active
      shell: 'aa-status --profiled'
      register: result
      failed_when: false
      changed_when: result.stdout|int != var_aa_profiled
    - name: Ensure apparmor is active Enforced @apparmor_is_active
      shell: 'aa-status --enforced'
      register: result
      failed_when: false
      changed_when: result.stdout|int != var_aa_enforced
    - name: Ensure apparmor is active Complaining @apparmor_is_active
      shell: 'aa-status --complaining'
      register: result
      failed_when: false
      changed_when: result.stdout|int != var_aa_complaining
  when: ansible_os_family in ['Debian']
  tags:
    - ws
    - sec
    - apparmor_is_active

- name: Apparmor complain @apparmor_complain
  ignore_errors: "{{ansible_check_mode}}"
  command: "aa-complain {{item}}"
  failed_when: false
  with_items:
    - cupsd
  when: ansible_os_family in ['Debian']
  tags:
    - ws
    - sec
    - apparmor_complain
