- name: Check lock-session policy @install_python_lxml
  ignore_errors: "{{ansible_check_mode}}"
  package:
    name: python3-lxml
    state: present
  tags:
    - ws
    - sec
    - install_python_lxml

- name: Check lock-session policy Xml @check_lock_session_policy
  ignore_errors: "{{ansible_check_mode}}"
  xml:
    path: /usr/share/polkit-1/actions/org.freedesktop.login1.policy
    xpath: /policyconfig/action[@id="org.freedesktop.login1.lock-sessions"]/defaults/{{item}}
    value: "auth_admin_keep"
  with_items:
    - allow_active
    - allow_inactive
    - allow_any
  tags:
    - ws
    - sec
    - check_lock_session_policy

- name: Suspend disallow policy @suspend_disallow_policy
  ignore_errors: true
  xml:
    path: /usr/share/polkit-1/actions/org.freedesktop.login1.policy
    xpath: /policyconfig/action[@id="org.freedesktop.login1.{{item}}"]/defaults/allow_active
    value: "no"
  with_items:
    - suspend
    - suspend-multiple-sessions
    - hibernate
    - hibernate-multiple-sessions
  tags:
    - ws
    - suspend_disallow_policy    

- name: Disable NetworkManager for user @nm_disallow_policy
  ignore_errors: true
  block:
    - name: Disable NetworkManager for user Disallow @nm_disallow_policy
      ignore_errors: true # workaround for ubuntu 20.04
      xml:
        path: /usr/share/polkit-1/actions/org.freedesktop.NetworkManager.policy
        xpath: /policyconfig/action/defaults/allow_active
        value: 'no'
      notify: NetworkManager restarted
  tags:
    - ws
    - nm_disallow_policy
