- name: Depmod
  command: depmod -ae

- name: Update initramfs
  command: update-initramfs -k all -u

- name: Dracut update
  command: dracut -f

- name: Usbguard restarted
  ignore_errors: "{{ansible_check_mode}}"
  service:
    name: usbguard
    state: restarted